# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 12:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomSeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', models.CharField(max_length=50)),
                ('holder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='random_seed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
